# build.yaml (project root)
# Source: https://drift.simonbinder.eu/generation_options/
targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
